In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
x = tf.Variable([2, 3, 5, 6, 8, 9, 12, 54, 65, 87], dtype='int32')
y = x * x
d = 2 * x
z = y + d
print(x)
print(y)
print(d)
print(z)

<tf.Variable 'Variable:0' shape=(10,) dtype=int32, numpy=array([ 2,  3,  5,  6,  8,  9, 12, 54, 65, 87], dtype=int32)>
tf.Tensor([   4    9   25   36   64   81  144 2916 4225 7569], shape=(10,), dtype=int32)
tf.Tensor([  4   6  10  12  16  18  24 108 130 174], shape=(10,), dtype=int32)
tf.Tensor([   8   15   35   48   80   99  168 3024 4355 7743], shape=(10,), dtype=int32)


In [ ]:
c = tf.constant(5, dtype = 'float64')
print(c)
n = np.arange(0, 13)
print(n)
n = tf.constant(n)
print(n)
n_float = tf.cast(n, dtype = 'float32')
print(n_float)

tf.Tensor(5.0, shape=(), dtype=float64)
[ 0  1  2  3  4  5  6  7  8  9 10 11 12]
tf.Tensor([ 0  1  2  3  4  5  6  7  8  9 10 11 12], shape=(13,), dtype=int64)
tf.Tensor([ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12.], shape=(13,), dtype=float32)


In [ ]:
x2 = tf.square(x)
y = tf.reshape(y, (2, 5))
x2 = tf.reshape(x2, (2, 5))
print(y)
print(x2)
z = 0;
if tf.reduce_all(tf.equal(y, x2)):
  print("Yes they are same.")

tf.Tensor(
[[   4    9   25   36   64]
 [  81  144 2916 4225 7569]], shape=(2, 5), dtype=int32)
tf.Tensor(
[[   4    9   25   36   64]
 [  81  144 2916 4225 7569]], shape=(2, 5), dtype=int32)
Yes they are same.


In [ ]:
print(c)

tf.Tensor(5.0, shape=(), dtype=float64)


In [ ]:
mul = tf.multiply(x, d)
print(mul)

tf.Tensor([    8    18    50    72   128   162   288  5832  8450 15138], shape=(10,), dtype=int32)


In [ ]:
# xs = np.array([5.0, 6.0, 7.0, 8.0 ,9.0, 10.0], dtype=float)
# ys = np.array([9.0, 11.0, 13.0, 15.0, 17.0, 19.0], dtype=float)

# w = tf.Variable(np.random.rand(), trainable = True)
# b = tf.Variable(np.random.rand(), trainable = True)

In [ ]:
# def myLoss(real_y, pred_y):
#   comp = real_y - pred_y
#   return tf.abs(comp)

# LEARNING_RATE = 0.001

In [ ]:
# def fitData(data_x, data_y):
#   with tf.GradientTape(persistent=True) as gt:
#     y_pred = w * data_x + b

#     loss = myLoss(data_y, y_pred)
#   gradientW = gt.gradient(loss, w)
#   gradientB = gt.gradient(loss, b)
#   w.assign_sub(gradientW * LEARNING_RATE)
#   b.assign_sub(gradientB * LEARNING_RATE)

In [ ]:
hello = tf.ones((2,2))

with tf.GradientTape(persistent = True) as gt:
  gt.watch(hello)
  shello= tf.reduce_sum(hello)
  fhello = tf.square(shello)
dfhello_dhello  = gt.gradient(fhello, hello)
print(dfhello_dhello)


tf.Tensor(
[[8. 8.]
 [8. 8.]], shape=(2, 2), dtype=float32)


In [ ]:
var_x = tf.constant(3.0)
with tf.GradientTape(persistent = True) as gt:
  gt.watch(var_x)
  var_y = var_x * var_x
  var_z = var_y * var_y
dz_dx = gt.gradient(var_z, var_x)
print(dz_dx)
dy_dx = gt.gradient(var_y, var_x)
print(dy_dx)

tf.Tensor(108.0, shape=(), dtype=float32)
tf.Tensor(6.0, shape=(), dtype=float32)


## Nested Gradient

In [ ]:
vx = tf.Variable(3)
with tf.GradientTape() as gt:
  with tf.GradientTape() as gt2:
    vy = vx * vx * vx
  dr_df = gt2.gradient(vy, vx)
d2y_dx2 = gt.gradient(dr_df, vx)

print(dy_dx)
print(d2y_dx2)

TypeError: ignored

just have a look and remember to write numbers correctly. =>

In [ ]:
vx = tf.Variable(3.0)
with tf.GradientTape() as gt:
  with tf.GradientTape() as gt2:
    vy = vx * vx * vx
  dr_df = gt2.gradient(vy, vx)
d2y_dx2 = gt.gradient(dr_df, vx)

print(dr_df)
print(d2y_dx2)

tf.Tensor(27.0, shape=(), dtype=float32)
tf.Tensor(18.0, shape=(), dtype=float32)
